apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: devolon
deploy:
  kubectl:
    manifests:
      - deployment.yaml
build:
  local:
    push: false
  artifacts:
    - image: devolon-laravel
      context: kubernetes/docker
      docker:
        dockerfile: Dockerfile
